//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democratic.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democratic.Idiomas.EnglishMessage", typeof(EnglishMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password could not be updated.
        /// </summary>
        internal static string mjsactuer {
            get {
                return ResourceManager.GetString("mjsactuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password not sent.
        /// </summary>
        internal static string mjsconen {
            get {
                return ResourceManager.GetString("mjsconen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message not sent.
        /// </summary>
        internal static string mjsmesageno {
            get {
                return ResourceManager.GetString("mjsmesageno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting record deleted.
        /// </summary>
        internal static string msjactaeliminada {
            get {
                return ResourceManager.GetString("msjactaeliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting record could not be deleted because of dependent data.
        /// </summary>
        internal static string msjactanoeliminada {
            get {
                return ResourceManager.GetString("msjactanoeliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting record could not be entered.
        /// </summary>
        internal static string msjactanoingresada {
            get {
                return ResourceManager.GetString("msjactanoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting record could not be updated.
        /// </summary>
        internal static string msjactanoupdate {
            get {
                return ResourceManager.GetString("msjactanoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User status is Active.
        /// </summary>
        internal static string msjactivo {
            get {
                return ResourceManager.GetString("msjactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, your access level is: Administrator.
        /// </summary>
        internal static string msjadmind {
            get {
                return ResourceManager.GetString("msjadmind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check with your administrator.
        /// </summary>
        internal static string msjadminpu {
            get {
                return ResourceManager.GetString("msjadminpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating organization.
        /// </summary>
        internal static string msjadminputitle {
            get {
                return ResourceManager.GetString("msjadminputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string msjadvertencia {
            get {
                return ResourceManager.GetString("msjadvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email entered in the first use must be the same as the email entered in the user.
        /// </summary>
        internal static string msjbademailpuser {
            get {
                return ResourceManager.GetString("msjbademailpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong E-Mail.
        /// </summary>
        internal static string msjbademailpusertitle {
            get {
                return ResourceManager.GetString("msjbademailpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blanks, check if you have entered an email.
        /// </summary>
        internal static string msjblank {
            get {
                return ResourceManager.GetString("msjblank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to eliminate the option group: .
        /// </summary>
        internal static string msjcadidatoselimited {
            get {
                return ResourceManager.GetString("msjcadidatoselimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required correlation field.
        /// </summary>
        internal static string msjcampocorrelativo {
            get {
                return ResourceManager.GetString("msjcampocorrelativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required option fields.
        /// </summary>
        internal static string msjcamposnecesarios {
            get {
                return ResourceManager.GetString("msjcamposnecesarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required user field.
        /// </summary>
        internal static string msjcamusu {
            get {
                return ResourceManager.GetString("msjcamusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key field required.
        /// </summary>
        internal static string msjcamusu2 {
            get {
                return ResourceManager.GetString("msjcamusu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option eliminated.
        /// </summary>
        internal static string msjcandidatoeliminado {
            get {
                return ResourceManager.GetString("msjcandidatoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option could not be updated.
        /// </summary>
        internal static string msjcandidatonoactualizado {
            get {
                return ResourceManager.GetString("msjcandidatonoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option could not be deleted because of dependent data.
        /// </summary>
        internal static string msjcandidatonoeliminado {
            get {
                return ResourceManager.GetString("msjcandidatonoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option could not be entered.
        /// </summary>
        internal static string msjcandidatonoingresado {
            get {
                return ResourceManager.GetString("msjcandidatonoingresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All options were eliminated.
        /// </summary>
        internal static string msjcandidatoseliminados {
            get {
                return ResourceManager.GetString("msjcandidatoseliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options could not be eliminated.
        /// </summary>
        internal static string msjcandidatosnoeliminados {
            get {
                return ResourceManager.GetString("msjcandidatosnoeliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blanks, check.
        /// </summary>
        internal static string msjchema {
            get {
                return ResourceManager.GetString("msjchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a check your credentials i have try again.
        /// </summary>
        internal static string msjcheyo {
            get {
                return ResourceManager.GetString("msjcheyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing user data.
        /// </summary>
        internal static string msjcheyo2 {
            get {
                return ResourceManager.GetString("msjcheyo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection could not be established.
        /// </summary>
        internal static string msjconexionno {
            get {
                return ResourceManager.GetString("msjconexionno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful connection.
        /// </summary>
        internal static string msjconexionsi {
            get {
                return ResourceManager.GetString("msjconexionsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the option group:.
        /// </summary>
        internal static string msjConfirmationP {
            get {
                return ResourceManager.GetString("msjConfirmationP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        internal static string msjConfirmationPTitle {
            get {
                return ResourceManager.GetString("msjConfirmationPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to eliminate the Report?.
        /// </summary>
        internal static string msjconfirmeliminaracta {
            get {
                return ResourceManager.GetString("msjconfirmeliminaracta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the email you want to send the password to.
        /// </summary>
        internal static string msjcore {
            get {
                return ResourceManager.GetString("msjcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful creation.
        /// </summary>
        internal static string msjcreaex {
            get {
                return ResourceManager.GetString("msjcreaex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Voting Venue Data.
        /// </summary>
        internal static string msjcvdatosfaltan {
            get {
                return ResourceManager.GetString("msjcvdatosfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting venue eliminated.
        /// </summary>
        internal static string msjcveliminado {
            get {
                return ResourceManager.GetString("msjcveliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required Voting Venue Fields.
        /// </summary>
        internal static string msjcvnecesario {
            get {
                return ResourceManager.GetString("msjcvnecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting venue could not be updated.
        /// </summary>
        internal static string msjcvnoactualizado {
            get {
                return ResourceManager.GetString("msjcvnoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The voting venue could not be removed.
        /// </summary>
        internal static string msjcvnoeliminado {
            get {
                return ResourceManager.GetString("msjcvnoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting venue could not be entered into the registry.
        /// </summary>
        internal static string msjcvnoregistrado {
            get {
                return ResourceManager.GetString("msjcvnoregistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while connecting to the database, check your internet access or that the server&apos;s servers are active..
        /// </summary>
        internal static string msjDatabaseP {
            get {
                return ResourceManager.GetString("msjDatabaseP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Critical error.
        /// </summary>
        internal static string msjDatabasePTitle {
            get {
                return ResourceManager.GetString("msjDatabasePTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Data Report.
        /// </summary>
        internal static string msjdatosfaltantes {
            get {
                return ResourceManager.GetString("msjdatosfaltantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data of the option.
        /// </summary>
        internal static string msjdatosfaltantescandidato {
            get {
                return ResourceManager.GetString("msjdatosfaltantescandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminated option group.
        /// </summary>
        internal static string msjDeletedP {
            get {
                return ResourceManager.GetString("msjDeletedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be deleted due to dependent data..
        /// </summary>
        internal static string msjdepedi {
            get {
                return ResourceManager.GetString("msjdepedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data entry fields.
        /// </summary>
        internal static string msjdetalleactanodatos {
            get {
                return ResourceManager.GetString("msjdetalleactanodatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details of the record could not be entered.
        /// </summary>
        internal static string msjdetalleactanoingresada {
            get {
                return ResourceManager.GetString("msjdetalleactanoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing details, check if a description has been added to the member.
        /// </summary>
        internal static string msjdetallemdatosfaltan {
            get {
                return ResourceManager.GetString("msjdetallemdatosfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail of deleted member.
        /// </summary>
        internal static string msjdetallemeliminado {
            get {
                return ResourceManager.GetString("msjdetallemeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member detail could not be updated.
        /// </summary>
        internal static string msjdetallemiembronoactualizado {
            get {
                return ResourceManager.GetString("msjdetallemiembronoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member detail could not be entered.
        /// </summary>
        internal static string msjdetallemiembronoingresado {
            get {
                return ResourceManager.GetString("msjdetallemiembronoingresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member detail could not be removed.
        /// </summary>
        internal static string msjdetallemnoeliminado {
            get {
                return ResourceManager.GetString("msjdetallemnoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record could not be updated.
        /// </summary>
        internal static string msjdetallenoupdated {
            get {
                return ResourceManager.GetString("msjdetallenoupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed process.
        /// </summary>
        internal static string msjDeteledPTitle {
            get {
                return ResourceManager.GetString("msjDeteledPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the member may have died.
        /// </summary>
        internal static string msjDiedM {
            get {
                return ResourceManager.GetString("msjDiedM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading at least one of the two lists, consult your administrator.
        /// </summary>
        internal static string msjdoslistas {
            get {
                return ResourceManager.GetString("msjdoslistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID document not found.
        /// </summary>
        internal static string msjduico {
            get {
                return ResourceManager.GetString("msjduico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong ID document, check your credentials I have tried again.
        /// </summary>
        internal static string msjduiin {
            get {
                return ResourceManager.GetString("msjduiin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing Member Data.
        /// </summary>
        internal static string msjduimiembrotitle {
            get {
                return ResourceManager.GetString("msjduimiembrotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID document field required.
        /// </summary>
        internal static string msjduinecesario {
            get {
                return ResourceManager.GetString("msjduinecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ID document or OCR Code field has not been entered..
        /// </summary>
        internal static string msjduiocr {
            get {
                return ResourceManager.GetString("msjduiocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong ID document, check your credentials and try again.
        /// </summary>
        internal static string msjduipuser {
            get {
                return ResourceManager.GetString("msjduipuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID document not found.
        /// </summary>
        internal static string msjduipusertitle {
            get {
                return ResourceManager.GetString("msjduipusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string msjE {
            get {
                return ResourceManager.GetString("msjE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Deleted.
        /// </summary>
        internal static string msjeliusu {
            get {
                return ResourceManager.GetString("msjeliusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee could not be removed due to dependent data.
        /// </summary>
        internal static string msjEmployedP {
            get {
                return ResourceManager.GetString("msjEmployedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process interrupted.
        /// </summary>
        internal static string msjEmployedPTitle {
            get {
                return ResourceManager.GetString("msjEmployedPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading images.
        /// </summary>
        internal static string msjerima {
            get {
                return ResourceManager.GetString("msjerima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert error.
        /// </summary>
        internal static string msjerint {
            get {
                return ResourceManager.GetString("msjerint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading at least one of the four lists, check with your administrator.
        /// </summary>
        internal static string msjerrocag {
            get {
                return ResourceManager.GetString("msjerrocag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error.
        /// </summary>
        internal static string msjerrorconexion {
            get {
                return ResourceManager.GetString("msjerrorconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load Option group status list, check with your administrator.
        /// </summary>
        internal static string msjErrorListP {
            get {
                return ResourceManager.GetString("msjErrorListP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load member status list, check with admin.
        /// </summary>
        internal static string msjErrorM {
            get {
                return ResourceManager.GetString("msjErrorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while checking hours.
        /// </summary>
        internal static string msjerrorrevisarhora {
            get {
                return ResourceManager.GetString("msjerrorrevisarhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading at least one of the three lists, consult with the administrator.
        /// </summary>
        internal static string msjerrortreslistas {
            get {
                return ResourceManager.GetString("msjerrortreslistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection error.
        /// </summary>
        internal static string msjerselecio {
            get {
                return ResourceManager.GetString("msjerselecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user entered is inactive, wait for lockout time or contact your admin.
        /// </summary>
        internal static string msjestadoinactivo {
            get {
                return ResourceManager.GetString("msjestadoinactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactive Status.
        /// </summary>
        internal static string msjestadoinactivotitle {
            get {
                return ResourceManager.GetString("msjestadoinactivotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excellent! the user entered already exists in the database, your new password has been sent to your email, User Found.
        /// </summary>
        internal static string msjexele {
            get {
                return ResourceManager.GetString("msjexele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to eliminate:.
        /// </summary>
        internal static string msjextraño {
            get {
                return ResourceManager.GetString("msjextraño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string msjextraño2 {
            get {
                return ResourceManager.GetString("msjextraño2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option images are missing.
        /// </summary>
        internal static string msjfalta {
            get {
                return ResourceManager.GetString("msjfalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To configure the organization be sure to enter all fields and upload an image.
        /// </summary>
        internal static string msjfaltadatapu {
            get {
                return ResourceManager.GetString("msjfaltadatapu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data.
        /// </summary>
        internal static string msjfaltadataputitle {
            get {
                return ResourceManager.GetString("msjfaltadataputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data.
        /// </summary>
        internal static string msjfaltan {
            get {
                return ResourceManager.GetString("msjfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data to enter, verify that all fields are filled.
        /// </summary>
        internal static string msjFieldsP {
            get {
                return ResourceManager.GetString("msjFieldsP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data from the query.
        /// </summary>
        internal static string msjfieldspu {
            get {
                return ResourceManager.GetString("msjfieldspu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option image required.
        /// </summary>
        internal static string msjimagencandidato {
            get {
                return ResourceManager.GetString("msjimagencandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image missing to enter, verify you have added an image.
        /// </summary>
        internal static string msjImageP {
            get {
                return ResourceManager.GetString("msjImageP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing image.
        /// </summary>
        internal static string msjImagePTitle {
            get {
                return ResourceManager.GetString("msjImagePTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been updated to an inactive status.
        /// </summary>
        internal static string msjinactiva {
            get {
                return ResourceManager.GetString("msjinactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated Status.
        /// </summary>
        internal static string msjinactivatitle {
            get {
                return ResourceManager.GetString("msjinactivatitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong email.
        /// </summary>
        internal static string msjinco {
            get {
                return ResourceManager.GetString("msjinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert error.
        /// </summary>
        internal static string msjinserterror {
            get {
                return ResourceManager.GetString("msjinserterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member could not be entered.
        /// </summary>
        internal static string msjInsertM {
            get {
                return ResourceManager.GetString("msjInsertM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option group could not be entered.
        /// </summary>
        internal static string msjInsertP {
            get {
                return ResourceManager.GetString("msjInsertP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be entered.
        /// </summary>
        internal static string msjinsertusererror {
            get {
                return ResourceManager.GetString("msjinsertusererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will have 5 chances in 3 minutes, please wait.
        /// </summary>
        internal static string msjintentosesperar {
            get {
                return ResourceManager.GetString("msjintentosesperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will have 5 more chances in 3 minutes.
        /// </summary>
        internal static string msjintentosesperarmas {
            get {
                return ResourceManager.GetString("msjintentosesperarmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time remaining.
        /// </summary>
        internal static string msjintentosesperartitle {
            get {
                return ResourceManager.GetString("msjintentosesperartitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout has expired, you have 5 more attempts.
        /// </summary>
        internal static string msjintentosmas {
            get {
                return ResourceManager.GetString("msjintentosmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time is up.
        /// </summary>
        internal static string msjintentosmastitle {
            get {
                return ResourceManager.GetString("msjintentosmastitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only have .
        /// </summary>
        internal static string msjintentosrestantes1 {
            get {
                return ResourceManager.GetString("msjintentosrestantes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  attempts to access..
        /// </summary>
        internal static string msjintentosrestantes2 {
            get {
                return ResourceManager.GetString("msjintentosrestantes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login error.
        /// </summary>
        internal static string msjintentosrestantestitle {
            get {
                return ResourceManager.GetString("msjintentosrestantestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load voting station list, check with administrator.
        /// </summary>
        internal static string msjJRVfailed {
            get {
                return ResourceManager.GetString("msjJRVfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad voting station mapping, please check your credentials and try again.
        /// </summary>
        internal static string msjJRVincorrecto {
            get {
                return ResourceManager.GetString("msjJRVincorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting station not found.
        /// </summary>
        internal static string msjJRVincorrectoTitle {
            get {
                return ResourceManager.GetString("msjJRVincorrectoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting station could not be entered.
        /// </summary>
        internal static string msjJRVnoingresada {
            get {
                return ResourceManager.GetString("msjJRVnoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error when loading the lists.
        /// </summary>
        internal static string msjlistas {
            get {
                return ResourceManager.GetString("msjlistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more lists could not be loaded into the system.
        /// </summary>
        internal static string msjlistasnocargadas {
            get {
                return ResourceManager.GetString("msjlistasnocargadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User logged in, root user has been created.
        /// </summary>
        internal static string msjloggedpuser {
            get {
                return ResourceManager.GetString("msjloggedpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful creation.
        /// </summary>
        internal static string msjloggedpusertitle {
            get {
                return ResourceManager.GetString("msjloggedpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All the elements are required..
        /// </summary>
        internal static string msjLogin {
            get {
                return ResourceManager.GetString("msjLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string msjLoginTitle {
            get {
                return ResourceManager.GetString("msjLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail not found.
        /// </summary>
        internal static string msjmailno {
            get {
                return ResourceManager.GetString("msjmailno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the member you want to join is a minor.
        /// </summary>
        internal static string msjMenorM {
            get {
                return ResourceManager.GetString("msjMenorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, you are a member of a voting station.
        /// </summary>
        internal static string msjmiembro {
            get {
                return ResourceManager.GetString("msjmiembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The logged in member has an inactive status.
        /// </summary>
        internal static string msjMinactivo {
            get {
                return ResourceManager.GetString("msjMinactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be updated.
        /// </summary>
        internal static string msjnoactualizado {
            get {
                return ResourceManager.GetString("msjnoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update error.
        /// </summary>
        internal static string msjnoactualizadotitle {
            get {
                return ResourceManager.GetString("msjnoactualizadotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User login, voting user has been created.
        /// </summary>
        internal static string msjnoi {
            get {
                return ResourceManager.GetString("msjnoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong OCR Code, check your credentials I have tried again.
        /// </summary>
        internal static string msjOCR {
            get {
                return ResourceManager.GetString("msjOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCR Code not found.
        /// </summary>
        internal static string msjOCRTitle {
            get {
                return ResourceManager.GetString("msjOCRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while connecting to the database, check 
        ///your internet Access or that the server services are active.
        /// </summary>
        internal static string msjocubase {
            get {
                return ResourceManager.GetString("msjocubase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem adding the ballot.
        /// </summary>
        internal static string msjocubol {
            get {
                return ResourceManager.GetString("msjocubol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, Option group.
        /// </summary>
        internal static string msjpartido {
            get {
                return ResourceManager.GetString("msjpartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        internal static string msjpassbadpuser {
            get {
                return ResourceManager.GetString("msjpassbadpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect passwords.
        /// </summary>
        internal static string msjpassbadpusertitle {
            get {
                return ResourceManager.GetString("msjpassbadpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection to the database was lost..
        /// </summary>
        internal static string msjperdioconexion {
            get {
                return ResourceManager.GetString("msjperdioconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access Denied.
        /// </summary>
        internal static string msjperdioconexiontitle {
            get {
                return ResourceManager.GetString("msjperdioconexiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, Supervisor.
        /// </summary>
        internal static string msjpresi {
            get {
                return ResourceManager.GetString("msjpresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your vote was successfully recorded in the system.
        /// </summary>
        internal static string msjprocom {
            get {
                return ResourceManager.GetString("msjprocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process interrupted.
        /// </summary>
        internal static string msjproint {
            get {
                return ResourceManager.GetString("msjproint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed process.
        /// </summary>
        internal static string msjproint2 {
            get {
                return ResourceManager.GetString("msjproint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted.
        /// </summary>
        internal static string msjregistroeliminado {
            get {
                return ResourceManager.GetString("msjregistroeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record could not be deleted because of dependent data.
        /// </summary>
        internal static string msjregistronoeliminado {
            get {
                return ResourceManager.GetString("msjregistronoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, your access level is: Root.
        /// </summary>
        internal static string msjroot {
            get {
                return ResourceManager.GetString("msjroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Be sure to save all data to avoid loss of information.
        /// </summary>
        internal static string msjseguro {
            get {
                return ResourceManager.GetString("msjseguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Application.
        /// </summary>
        internal static string msjsegurotitle {
            get {
                return ResourceManager.GetString("msjsegurotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when selecting an empty cell \ n \ ntry to select a cell with an existing data.
        /// </summary>
        internal static string msjselec {
            get {
                return ResourceManager.GetString("msjselec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the organization has not been configured.
        /// </summary>
        internal static string msjtribnocreatepu {
            get {
                return ResourceManager.GetString("msjtribnocreatepu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inconsistent dates.
        /// </summary>
        internal static string msjtribnocreateputitle {
            get {
                return ResourceManager.GetString("msjtribnocreateputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the Organization may not have existed.
        /// </summary>
        internal static string msjtribnoexistpu {
            get {
                return ResourceManager.GetString("msjtribnoexistpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization image missing.
        /// </summary>
        internal static string msjtribuimgpu {
            get {
                return ResourceManager.GetString("msjtribuimgpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! An error occurred while loading the organization image.
        /// </summary>
        internal static string msjtribunal {
            get {
                return ResourceManager.GetString("msjtribunal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization could not be configured.
        /// </summary>
        internal static string msjtribunalerrorpu {
            get {
                return ResourceManager.GetString("msjtribunalerrorpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more option images were not uploaded.
        /// </summary>
        internal static string msjunai {
            get {
                return ResourceManager.GetString("msjunai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be updated.
        /// </summary>
        internal static string msjUpdM {
            get {
                return ResourceManager.GetString("msjUpdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option group could not be updated.
        /// </summary>
        internal static string msjUpdP {
            get {
                return ResourceManager.GetString("msjUpdP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong username or password, check your credentials.
        /// </summary>
        internal static string msjuserdenied {
            get {
                return ResourceManager.GetString("msjuserdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No user found, check if you have entered the correct user.
        /// </summary>
        internal static string msjusernoencontrado {
            get {
                return ResourceManager.GetString("msjusernoencontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong user.
        /// </summary>
        internal static string msjusernoencontradotitle {
            get {
                return ResourceManager.GetString("msjusernoencontradotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User, registration could not be updated.
        /// </summary>
        internal static string msjusuarionoactualizado {
            get {
                return ResourceManager.GetString("msjusuarionoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be entered.
        /// </summary>
        internal static string msjusunop {
            get {
                return ResourceManager.GetString("msjusunop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User could not be updated.
        /// </summary>
        internal static string msjusunop2 {
            get {
                return ResourceManager.GetString("msjusunop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty fields.
        /// </summary>
        internal static string msjvaciotitle {
            get {
                return ResourceManager.GetString("msjvaciotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification error occurred, check with your administrator.
        /// </summary>
        internal static string msjverificar {
            get {
                return ResourceManager.GetString("msjverificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error information.
        /// </summary>
        internal static string msjverificartitle {
            get {
                return ResourceManager.GetString("msjverificartitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, Auditor.
        /// </summary>
        internal static string msjvice {
            get {
                return ResourceManager.GetString("msjvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome Voter.
        /// </summary>
        internal static string msjvotante {
            get {
                return ResourceManager.GetString("msjvotante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote could not be entered.
        /// </summary>
        internal static string msjvtin {
            get {
                return ResourceManager.GetString("msjvtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote recorded.
        /// </summary>
        internal static string msjvtin2 {
            get {
                return ResourceManager.GetString("msjvtin2", resourceCulture);
            }
        }
    }
}
