//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democratic.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democratic.Idiomas.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Act.
        /// </summary>
        internal static string btnactas {
            get {
                return ResourceManager.GetString("btnactas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update report.
        /// </summary>
        internal static string BtnActualizarActa {
            get {
                return ResourceManager.GetString("BtnActualizarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update option.
        /// </summary>
        internal static string BtnActualizarCandidato {
            get {
                return ResourceManager.GetString("BtnActualizarCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update voting venue.
        /// </summary>
        internal static string BtnActualizarCV {
            get {
                return ResourceManager.GetString("BtnActualizarCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update report detail.
        /// </summary>
        internal static string BtnActualizarDetalleA {
            get {
                return ResourceManager.GetString("BtnActualizarDetalleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update member detail.
        /// </summary>
        internal static string BtnActualizarDetalleM {
            get {
                return ResourceManager.GetString("BtnActualizarDetalleM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update voting station.
        /// </summary>
        internal static string BtnActualizarJRV {
            get {
                return ResourceManager.GetString("BtnActualizarJRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update member.
        /// </summary>
        internal static string BtnActualizarM {
            get {
                return ResourceManager.GetString("BtnActualizarM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update option group.
        /// </summary>
        internal static string BtnActualizarPartido {
            get {
                return ResourceManager.GetString("BtnActualizarPartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update User.
        /// </summary>
        internal static string btnactualizarusuario {
            get {
                return ResourceManager.GetString("btnactualizarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Act.
        /// </summary>
        internal static string btnadmindactas {
            get {
                return ResourceManager.GetString("btnadmindactas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Members and Users.
        /// </summary>
        internal static string btnadmindmiembrosanduser {
            get {
                return ResourceManager.GetString("btnadmindmiembrosanduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Option Groups and Options.
        /// </summary>
        internal static string btnadmindpartidosycandidatos {
            get {
                return ResourceManager.GetString("btnadmindpartidosycandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add report.
        /// </summary>
        internal static string BtnAgregarActa {
            get {
                return ResourceManager.GetString("BtnAgregarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add option.
        /// </summary>
        internal static string BtnAgregarCandidato {
            get {
                return ResourceManager.GetString("BtnAgregarCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add report detail.
        /// </summary>
        internal static string BtnAgregarDetalleA {
            get {
                return ResourceManager.GetString("BtnAgregarDetalleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add member detail.
        /// </summary>
        internal static string BtnAgregarDetalleM {
            get {
                return ResourceManager.GetString("BtnAgregarDetalleM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add member.
        /// </summary>
        internal static string BtnAgregarM {
            get {
                return ResourceManager.GetString("BtnAgregarM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add option group.
        /// </summary>
        internal static string BtnAgregarPartido {
            get {
                return ResourceManager.GetString("BtnAgregarPartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add User.
        /// </summary>
        internal static string btnagregarusuario {
            get {
                return ResourceManager.GetString("btnagregarusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string BtnBuscar {
            get {
                return ResourceManager.GetString("BtnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string btncandidato {
            get {
                return ResourceManager.GetString("btncandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load image.
        /// </summary>
        internal static string BtnCargarImageC {
            get {
                return ResourceManager.GetString("BtnCargarImageC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload image.
        /// </summary>
        internal static string btncargarimagen {
            get {
                return ResourceManager.GetString("btncargarimagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btncerrar {
            get {
                return ResourceManager.GetString("btncerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test.
        /// </summary>
        internal static string btnconectar {
            get {
                return ResourceManager.GetString("btnconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string btncontinuar {
            get {
                return ResourceManager.GetString("btncontinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting Venues.
        /// </summary>
        internal static string btncv {
            get {
                return ResourceManager.GetString("btncv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Act Details.
        /// </summary>
        internal static string btndetalleacta {
            get {
                return ResourceManager.GetString("btndetalleacta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members Detail.
        /// </summary>
        internal static string btndetallemiembros {
            get {
                return ResourceManager.GetString("btndetallemiembros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete user.
        /// </summary>
        internal static string BtnEliminarActa {
            get {
                return ResourceManager.GetString("BtnEliminarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete option.
        /// </summary>
        internal static string BtnEliminarCandidato {
            get {
                return ResourceManager.GetString("BtnEliminarCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete voting venue.
        /// </summary>
        internal static string BtnEliminarCV {
            get {
                return ResourceManager.GetString("BtnEliminarCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete report detail.
        /// </summary>
        internal static string BtnEliminarDetalleA {
            get {
                return ResourceManager.GetString("BtnEliminarDetalleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete voting station.
        /// </summary>
        internal static string BtnEliminarJRV {
            get {
                return ResourceManager.GetString("BtnEliminarJRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove option group.
        /// </summary>
        internal static string BtnEliminarPartido {
            get {
                return ResourceManager.GetString("BtnEliminarPartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Structure.
        /// </summary>
        internal static string btnestructura {
            get {
                return ResourceManager.GetString("btnestructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string btnexit {
            get {
                return ResourceManager.GetString("btnexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Password.
        /// </summary>
        internal static string BtnGenerar {
            get {
                return ResourceManager.GetString("BtnGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add voting venue.
        /// </summary>
        internal static string BtnIngresarCV {
            get {
                return ResourceManager.GetString("BtnIngresarCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add voting station.
        /// </summary>
        internal static string BtnIngresarJRV {
            get {
                return ResourceManager.GetString("BtnIngresarJRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing In.
        /// </summary>
        internal static string btnIniciar {
            get {
                return ResourceManager.GetString("btnIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting stations.
        /// </summary>
        internal static string btnjrv {
            get {
                return ResourceManager.GetString("btnjrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Voting Stations and Voting Venues.
        /// </summary>
        internal static string btnjrvandcv {
            get {
                return ResourceManager.GetString("btnjrvandcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean boxes.
        /// </summary>
        internal static string BtnLimpiar {
            get {
                return ResourceManager.GetString("BtnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean report.
        /// </summary>
        internal static string BtnLimpiarActa {
            get {
                return ResourceManager.GetString("BtnLimpiarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean fields.
        /// </summary>
        internal static string BtnLimpiarPartidos {
            get {
                return ResourceManager.GetString("BtnLimpiarPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximize.
        /// </summary>
        internal static string btnmaximizar {
            get {
                return ResourceManager.GetString("btnmaximizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Members.
        /// </summary>
        internal static string btnmiembros {
            get {
                return ResourceManager.GetString("btnmiembros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize.
        /// </summary>
        internal static string btnminimizar {
            get {
                return ResourceManager.GetString("btnminimizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        internal static string btnnormal {
            get {
                return ResourceManager.GetString("btnnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option groups.
        /// </summary>
        internal static string btnpartido {
            get {
                return ResourceManager.GetString("btnpartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure organization.
        /// </summary>
        internal static string btnprimeruso {
            get {
                return ResourceManager.GetString("btnprimeruso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create First User.
        /// </summary>
        internal static string btnprimerusuario {
            get {
                return ResourceManager.GetString("btnprimerusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend.
        /// </summary>
        internal static string btnreenviar {
            get {
                return ResourceManager.GetString("btnreenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        internal static string BtnRefrescarM {
            get {
                return ResourceManager.GetString("BtnRefrescarM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string BtnRegistrar {
            get {
                return ResourceManager.GetString("BtnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Conecction.
        /// </summary>
        internal static string btnrojo {
            get {
                return ResourceManager.GetString("btnrojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove all options.
        /// </summary>
        internal static string BtnTruncateC {
            get {
                return ResourceManager.GetString("BtnTruncateC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string btnusuarios {
            get {
                return ResourceManager.GetString("btnusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your Options.
        /// </summary>
        internal static string btnvercandidatos {
            get {
                return ResourceManager.GetString("btnvercandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection Exists.
        /// </summary>
        internal static string btnverde {
            get {
                return ResourceManager.GetString("btnverde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Stats.
        /// </summary>
        internal static string btnverestadisticas {
            get {
                return ResourceManager.GetString("btnverestadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote.
        /// </summary>
        internal static string btnvotar {
            get {
                return ResourceManager.GetString("btnvotar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Votes.
        /// </summary>
        internal static string btnvotos {
            get {
                return ResourceManager.GetString("btnvotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of votes of options.
        /// </summary>
        internal static string grpgraficas {
            get {
                return ResourceManager.GetString("grpgraficas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Members by ID Document Number.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail:.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affiliated option group.
        /// </summary>
        internal static string lblafiliado {
            get {
                return ResourceManager.GetString("lblafiliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surnames:.
        /// </summary>
        internal static string lblApe {
            get {
                return ResourceManager.GetString("lblApe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option last name.
        /// </summary>
        internal static string lblApellidoC {
            get {
                return ResourceManager.GetString("lblApellidoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member last name:.
        /// </summary>
        internal static string lblApellidoM {
            get {
                return ResourceManager.GetString("lblApellidoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search report.
        /// </summary>
        internal static string lblBuscar {
            get {
                return ResourceManager.GetString("lblBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search users:.
        /// </summary>
        internal static string lblBuscar2 {
            get {
                return ResourceManager.GetString("lblBuscar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search option.
        /// </summary>
        internal static string lblBuscarC {
            get {
                return ResourceManager.GetString("lblBuscarC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search voting venue.
        /// </summary>
        internal static string lblBuscarCV {
            get {
                return ResourceManager.GetString("lblBuscarCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search report details.
        /// </summary>
        internal static string lblBuscarDa {
            get {
                return ResourceManager.GetString("lblBuscarDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for an option group.
        /// </summary>
        internal static string lblBuscarDM {
            get {
                return ResourceManager.GetString("lblBuscarDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for voting station.
        /// </summary>
        internal static string lblBuscarjrv {
            get {
                return ResourceManager.GetString("lblBuscarjrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search option group.
        /// </summary>
        internal static string lblBuscarP {
            get {
                return ResourceManager.GetString("lblBuscarP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ballot quantity:.
        /// </summary>
        internal static string lblcantidad {
            get {
                return ResourceManager.GetString("lblcantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of ballots.
        /// </summary>
        internal static string lblCantidadBoleta {
            get {
                return ResourceManager.GetString("lblCantidadBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of voting stations.
        /// </summary>
        internal static string lblCantidadJRV {
            get {
                return ResourceManager.GetString("lblCantidadJRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of votes:.
        /// </summary>
        internal static string lblCantidadV {
            get {
                return ResourceManager.GetString("lblCantidadV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of votes:.
        /// </summary>
        internal static string lblCantidadVotos {
            get {
                return ResourceManager.GetString("lblCantidadVotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of ballots:.
        /// </summary>
        internal static string lblCBoletas {
            get {
                return ResourceManager.GetString("lblCBoletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting center:.
        /// </summary>
        internal static string lblcentrov {
            get {
                return ResourceManager.GetString("lblcentrov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting venue.
        /// </summary>
        internal static string lblcentrovotacion {
            get {
                return ResourceManager.GetString("lblcentrovotacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords match.
        /// </summary>
        internal static string lblcoincidencia {
            get {
                return ResourceManager.GetString("lblcoincidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Composition:.
        /// </summary>
        internal static string lblcomposicion {
            get {
                return ResourceManager.GetString("lblcomposicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (The password provided must
        ///be the one used to access the mail).
        /// </summary>
        internal static string Lblcontrainfo {
            get {
                return ResourceManager.GetString("Lblcontrainfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlative of voting station.
        /// </summary>
        internal static string lblcorrelative {
            get {
                return ResourceManager.GetString("lblcorrelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email: (required to send password).
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Mail:.
        /// </summary>
        internal static string lblcorreotribunalregister {
            get {
                return ResourceManager.GetString("lblcorreotribunalregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don´t have an account? So....
        /// </summary>
        internal static string lblcuenta {
            get {
                return ResourceManager.GetString("lblcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your E-mail:.
        /// </summary>
        internal static string lblCuenta2 {
            get {
                return ResourceManager.GetString("lblCuenta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth:.
        /// </summary>
        internal static string lblCump {
            get {
                return ResourceManager.GetString("lblCump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of voting venue.
        /// </summary>
        internal static string lblCV {
            get {
                return ResourceManager.GetString("lblCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate dark mode.
        /// </summary>
        internal static string lbldarkmode {
            get {
                return ResourceManager.GetString("lbldarkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member details:.
        /// </summary>
        internal static string lblDetalleM {
            get {
                return ResourceManager.GetString("lblDetalleM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        internal static string lblDirec {
            get {
                return ResourceManager.GetString("lblDirec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member address:.
        /// </summary>
        internal static string lblDireccionM {
            get {
                return ResourceManager.GetString("lblDireccionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the member&apos;s ID document:.
        /// </summary>
        internal static string lbldui {
            get {
                return ResourceManager.GetString("lbldui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID document:.
        /// </summary>
        internal static string lblDuiM {
            get {
                return ResourceManager.GetString("lblDuiM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting venue state.
        /// </summary>
        internal static string lblestado {
            get {
                return ResourceManager.GetString("lblestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option status.
        /// </summary>
        internal static string lblEstadoC {
            get {
                return ResourceManager.GetString("lblEstadoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member status:.
        /// </summary>
        internal static string lblEstadoM {
            get {
                return ResourceManager.GetString("lblEstadoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member status:.
        /// </summary>
        internal static string lblEstadoP {
            get {
                return ResourceManager.GetString("lblEstadoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option group status:.
        /// </summary>
        internal static string lblestadopartido {
            get {
                return ResourceManager.GetString("lblestadopartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User status:.
        /// </summary>
        internal static string lblEstadoU {
            get {
                return ResourceManager.GetString("lblEstadoU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User status:.
        /// </summary>
        internal static string lblestadouser {
            get {
                return ResourceManager.GetString("lblestadouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State of the voting station.
        /// </summary>
        internal static string lblestadovrb {
            get {
                return ResourceManager.GetString("lblestadovrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foundation date:.
        /// </summary>
        internal static string lblfecha {
            get {
                return ResourceManager.GetString("lblfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth:.
        /// </summary>
        internal static string lblFechaNM {
            get {
                return ResourceManager.GetString("lblFechaNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (When generating a password, it will be updated to the old password).
        /// </summary>
        internal static string lblgenerarc {
            get {
                return ResourceManager.GetString("lblgenerarc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        internal static string lblGenero {
            get {
                return ResourceManager.GetString("lblGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the correlative of the voting station:.
        /// </summary>
        internal static string lblidjrv {
            get {
                return ResourceManager.GetString("lblidjrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image max 4MB.
        /// </summary>
        internal static string lblimgmax {
            get {
                return ResourceManager.GetString("lblimgmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization image:.
        /// </summary>
        internal static string lblimgT {
            get {
                return ResourceManager.GetString("lblimgT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (The email provided will be used
        ///to contact other users.).
        /// </summary>
        internal static string lblinfo {
            get {
                return ResourceManager.GetString("lblinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Democratic is a configurable voting system based on templates.
        ///It lets you define vote options, organize voting tables and view
        ///result charts. It is built with C# and databases; the interfaces
        ///use Visual Studio 2015 and the Bunifu Framework v1.52..
        /// </summary>
        internal static string lblinfo1 {
            get {
                return ResourceManager.GetString("lblinfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The program was developed by the following programmers:
        ///
        ///- Eduardo Ernesto Vargas Hernández
        ///- Gabriela Susana Méndez Barrera
        ///- Lenny Adrián Elías Sánchez
        ///- Monica Abigail Mejía Mártinez.
        /// </summary>
        internal static string lblinfo2 {
            get {
                return ResourceManager.GetString("lblinfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string lblinfomation {
            get {
                return ResourceManager.GetString("lblinfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string lblinicio {
            get {
                return ResourceManager.GetString("lblinicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tried:.
        /// </summary>
        internal static string lblIntento {
            get {
                return ResourceManager.GetString("lblIntento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempts.
        /// </summary>
        internal static string lblintentos {
            get {
                return ResourceManager.GetString("lblintentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting station:.
        /// </summary>
        internal static string lblJRV {
            get {
                return ResourceManager.GetString("lblJRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voting station.
        /// </summary>
        internal static string lblJRVdm {
            get {
                return ResourceManager.GetString("lblJRVdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jurisdiction:.
        /// </summary>
        internal static string lbljurisdiccion {
            get {
                return ResourceManager.GetString("lbljurisdiccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key:.
        /// </summary>
        internal static string lblkey {
            get {
                return ResourceManager.GetString("lblkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member:.
        /// </summary>
        internal static string lblM {
            get {
                return ResourceManager.GetString("lblM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: Email must have less secure apps access enabled..
        /// </summary>
        internal static string lblmenosseguras {
            get {
                return ResourceManager.GetString("lblmenosseguras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member:.
        /// </summary>
        internal static string lblmiembro {
            get {
                return ResourceManager.GetString("lblmiembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show:.
        /// </summary>
        internal static string lblMostrar {
            get {
                return ResourceManager.GetString("lblMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipality.
        /// </summary>
        internal static string lblMunicipio {
            get {
                return ResourceManager.GetString("lblMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        internal static string lblnocoincidencia {
            get {
                return ResourceManager.GetString("lblnocoincidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Names:.
        /// </summary>
        internal static string lblnom {
            get {
                return ResourceManager.GetString("lblnom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option names.
        /// </summary>
        internal static string lblNombreC {
            get {
                return ResourceManager.GetString("lblNombreC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member name:.
        /// </summary>
        internal static string lblNombreMiembro {
            get {
                return ResourceManager.GetString("lblNombreMiembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option group name:.
        /// </summary>
        internal static string lblNombrep {
            get {
                return ResourceManager.GetString("lblNombrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number:.
        /// </summary>
        internal static string lblNume {
            get {
                return ResourceManager.GetString("lblNume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCR Code.
        /// </summary>
        internal static string lblOCR {
            get {
                return ResourceManager.GetString("lblOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string lblolvidar {
            get {
                return ResourceManager.GetString("lblolvidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country:.
        /// </summary>
        internal static string lblpais {
            get {
                return ResourceManager.GetString("lblpais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option group:.
        /// </summary>
        internal static string lblPartido {
            get {
                return ResourceManager.GetString("lblPartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        internal static string lblpass {
            get {
                return ResourceManager.GetString("lblpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password:.
        /// </summary>
        internal static string lblpassconfirm {
            get {
                return ResourceManager.GetString("lblpassconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization configuration.
        /// </summary>
        internal static string lblprimerU {
            get {
                return ResourceManager.GetString("lblprimerU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (previously given e-mail).
        /// </summary>
        internal static string lblproporcionado {
            get {
                return ResourceManager.GetString("lblproporcionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First User Configuration.
        /// </summary>
        internal static string lblpuser {
            get {
                return ResourceManager.GetString("lblpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 170x195 Recommendation.
        /// </summary>
        internal static string lblRecomendación {
            get {
                return ResourceManager.GetString("lblRecomendación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        internal static string lblrecuperarpass {
            get {
                return ResourceManager.GetString("lblrecuperarpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have not received the password, click resend.
        /// </summary>
        internal static string lblreenviar {
            get {
                return ResourceManager.GetString("lblreenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string lblregistrar {
            get {
                return ResourceManager.GetString("lblregistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meeting venue:.
        /// </summary>
        internal static string lblsede {
            get {
                return ResourceManager.GetString("lblsede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What is Democratic?.
        /// </summary>
        internal static string lbltema {
            get {
                return ResourceManager.GetString("lbltema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you do not have an account to
        ///access the system, you can use
        ///your ID number with the OCR Code
        ///(the second line on the back of
        ///your ID document) to access and
        ///participate in the active vote..
        /// </summary>
        internal static string lbltexto1 {
            get {
                return ResourceManager.GetString("lbltexto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can create your own account to access the voting system. With it
        ///you can cast your vote according to the configured template. Users with
        ///administration or table roles can manage options, voting tables and
        ///results before, during and after the voting process..
        /// </summary>
        internal static string lbltexto2 {
            get {
                return ResourceManager.GetString("lbltexto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization type:.
        /// </summary>
        internal static string lbltipo {
            get {
                return ResourceManager.GetString("lbltipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of user:.
        /// </summary>
        internal static string lbltipouser {
            get {
                return ResourceManager.GetString("lbltipouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization:.
        /// </summary>
        internal static string lblTribunal {
            get {
                return ResourceManager.GetString("lblTribunal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string lbluser {
            get {
                return ResourceManager.GetString("lbluser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string lbluser2 {
            get {
                return ResourceManager.GetString("lbluser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About the system.
        /// </summary>
        internal static string toolacerca {
            get {
                return ResourceManager.GetString("toolacerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string toolcerrar {
            get {
                return ResourceManager.GetString("toolcerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report bug.
        /// </summary>
        internal static string toolerror {
            get {
                return ResourceManager.GetString("toolerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string toolhelp {
            get {
                return ResourceManager.GetString("toolhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu.
        /// </summary>
        internal static string toolmenu {
            get {
                return ResourceManager.GetString("toolmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System technical requirements.
        /// </summary>
        internal static string toolreq {
            get {
                return ResourceManager.GetString("toolreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string toolsalir {
            get {
                return ResourceManager.GetString("toolsalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        internal static string toolsistema {
            get {
                return ResourceManager.GetString("toolsistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See help.
        /// </summary>
        internal static string toolverhelp {
            get {
                return ResourceManager.GetString("toolverhelp", resourceCulture);
            }
        }
    }
}
