//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democratic.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesEspanol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesEspanol() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democratic.Idiomas.MensajesEspanol", typeof(MensajesEspanol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de actualización.
        /// </summary>
        internal static string mjsactuer {
            get {
                return ResourceManager.GetString("mjsactuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no pudo ser actualizada.
        /// </summary>
        internal static string mjsco {
            get {
                return ResourceManager.GetString("mjsco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña no enviada.
        /// </summary>
        internal static string mjsconen {
            get {
                return ResourceManager.GetString("mjsconen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje no enviado.
        /// </summary>
        internal static string mjsmesageno {
            get {
                return ResourceManager.GetString("mjsmesageno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta eliminada.
        /// </summary>
        internal static string msjactaeliminada {
            get {
                return ResourceManager.GetString("msjactaeliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta no pudo ser eliminada debido a que existen datos dependientes..
        /// </summary>
        internal static string msjactanoeliminada {
            get {
                return ResourceManager.GetString("msjactanoeliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta no pudo ser ingresada.
        /// </summary>
        internal static string msjactanoingresada {
            get {
                return ResourceManager.GetString("msjactanoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acta no pudo ser actualizada.
        /// </summary>
        internal static string msjactanoupdate {
            get {
                return ResourceManager.GetString("msjactanoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado del usuario es Activo.
        /// </summary>
        internal static string msjactivo {
            get {
                return ResourceManager.GetString("msjactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, su nivel de acceso es: Administrador&quot;.
        /// </summary>
        internal static string msjadmind {
            get {
                return ResourceManager.GetString("msjadmind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulte con su administrador.
        /// </summary>
        internal static string msjadminpu {
            get {
                return ResourceManager.GetString("msjadminpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al configurar organización.
        /// </summary>
        internal static string msjadminputitle {
            get {
                return ResourceManager.GetString("msjadminputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string msjadvertencia {
            get {
                return ResourceManager.GetString("msjadvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado en el primer uso debe ser igual al correo ingresado en el usuario.
        /// </summary>
        internal static string msjbademailpuser {
            get {
                return ResourceManager.GetString("msjbademailpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo incorrecto.
        /// </summary>
        internal static string msjbademailpusertitle {
            get {
                return ResourceManager.GetString("msjbademailpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacios en blanco, verifique si ha ingresado un correo.
        /// </summary>
        internal static string msjblank {
            get {
                return ResourceManager.GetString("msjblank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de correlativo necesario.
        /// </summary>
        internal static string msjcampocorrelativo {
            get {
                return ResourceManager.GetString("msjcampocorrelativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos de opción necesarios.
        /// </summary>
        internal static string msjcamposnecesarios {
            get {
                return ResourceManager.GetString("msjcamposnecesarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de usuario necesario.
        /// </summary>
        internal static string msjcamusu {
            get {
                return ResourceManager.GetString("msjcamusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de clave necesario.
        /// </summary>
        internal static string msjcamusu2 {
            get {
                return ResourceManager.GetString("msjcamusu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción eliminada.
        /// </summary>
        internal static string msjcandidatoeliminado {
            get {
                return ResourceManager.GetString("msjcandidatoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no pudo ser actualizada.
        /// </summary>
        internal static string msjcandidatonoactualizado {
            get {
                return ResourceManager.GetString("msjcandidatonoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no pudo ser eliminada debido a que existen datos dependientes.
        /// </summary>
        internal static string msjcandidatonoeliminado {
            get {
                return ResourceManager.GetString("msjcandidatonoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no pudo ser ingresada.
        /// </summary>
        internal static string msjcandidatonoingresado {
            get {
                return ResourceManager.GetString("msjcandidatonoingresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las opciones fueron eliminadas.
        /// </summary>
        internal static string msjcandidatoseliminados {
            get {
                return ResourceManager.GetString("msjcandidatoseliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones no pudieron ser eliminadas.
        /// </summary>
        internal static string msjcandidatosnoeliminados {
            get {
                return ResourceManager.GetString("msjcandidatosnoeliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacios en blanco, verifique.
        /// </summary>
        internal static string msjchema {
            get {
                return ResourceManager.GetString("msjchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique sus credenciales he intentelo de nuevo.
        /// </summary>
        internal static string msjcheyo {
            get {
                return ResourceManager.GetString("msjcheyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes del usuario.
        /// </summary>
        internal static string msjcheyo2 {
            get {
                return ResourceManager.GetString("msjcheyo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer conexión.
        /// </summary>
        internal static string msjconexionno {
            get {
                return ResourceManager.GetString("msjconexionno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión exitosa.
        /// </summary>
        internal static string msjconexionsi {
            get {
                return ResourceManager.GetString("msjconexionsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de querer eliminar al grupo de opciones:.
        /// </summary>
        internal static string msjConfirmationP {
            get {
                return ResourceManager.GetString("msjConfirmationP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string msjConfirmationPTitle {
            get {
                return ResourceManager.GetString("msjConfirmationPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de querer eliminar la Acta?.
        /// </summary>
        internal static string msjconfirmeliminaracta {
            get {
                return ResourceManager.GetString("msjconfirmeliminaracta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el correo electronico al que desea enviar la contraseña.
        /// </summary>
        internal static string msjcore {
            get {
                return ResourceManager.GetString("msjcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación exitosa.
        /// </summary>
        internal static string msjcreaex {
            get {
                return ResourceManager.GetString("msjcreaex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes del Sede.
        /// </summary>
        internal static string msjcvdatosfaltan {
            get {
                return ResourceManager.GetString("msjcvdatosfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sede eliminado.
        /// </summary>
        internal static string msjcveliminado {
            get {
                return ResourceManager.GetString("msjcveliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos de Sede necesarios.
        /// </summary>
        internal static string msjcvnecesario {
            get {
                return ResourceManager.GetString("msjcvnecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sede no pudo ser actualizada.
        /// </summary>
        internal static string msjcvnoactualizado {
            get {
                return ResourceManager.GetString("msjcvnoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Sede no pudo ser eliminado.
        /// </summary>
        internal static string msjcvnoeliminado {
            get {
                return ResourceManager.GetString("msjcvnoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sede no pudo ser ingresado al registro.
        /// </summary>
        internal static string msjcvnoregistrado {
            get {
                return ResourceManager.GetString("msjcvnoregistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al establecer conexión con la base de datos, verifique su acceso a internet o que los servicios del seridor esten activos.
        /// </summary>
        internal static string msjDatabaseP {
            get {
                return ResourceManager.GetString("msjDatabaseP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Crítico.
        /// </summary>
        internal static string msjDatabasePTitle {
            get {
                return ResourceManager.GetString("msjDatabasePTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes de Actas.
        /// </summary>
        internal static string msjdatosfaltantes {
            get {
                return ResourceManager.GetString("msjdatosfaltantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes de la opción.
        /// </summary>
        internal static string msjdatosfaltantescandidato {
            get {
                return ResourceManager.GetString("msjdatosfaltantescandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de opciones eliminado.
        /// </summary>
        internal static string msjDeletedP {
            get {
                return ResourceManager.GetString("msjDeletedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser eliminado debido a que existen datos dependientes.
        /// </summary>
        internal static string msjdepedi {
            get {
                return ResourceManager.GetString("msjdepedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos faltantes de ingresar datos.
        /// </summary>
        internal static string msjdetalleactanodatos {
            get {
                return ResourceManager.GetString("msjdetalleactanodatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de acta no pudo ser ingresada.
        /// </summary>
        internal static string msjdetalleactanoingresada {
            get {
                return ResourceManager.GetString("msjdetalleactanoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes en los detalles, verifique si se ha agregado una descripción al miembro.
        /// </summary>
        internal static string msjdetallemdatosfaltan {
            get {
                return ResourceManager.GetString("msjdetallemdatosfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de miembro eliminado.
        /// </summary>
        internal static string msjdetallemeliminado {
            get {
                return ResourceManager.GetString("msjdetallemeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del miembro no pudo ser actualizado.
        /// </summary>
        internal static string msjdetallemiembronoactualizado {
            get {
                return ResourceManager.GetString("msjdetallemiembronoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del miembro no pudo ser ingresado.
        /// </summary>
        internal static string msjdetallemiembronoingresado {
            get {
                return ResourceManager.GetString("msjdetallemiembronoingresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de miembro no pudo ser eliminado.
        /// </summary>
        internal static string msjdetallemnoeliminado {
            get {
                return ResourceManager.GetString("msjdetallemnoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudo ser actualizado el registro.
        /// </summary>
        internal static string msjdetallenoupdated {
            get {
                return ResourceManager.GetString("msjdetallenoupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Completado.
        /// </summary>
        internal static string msjDeteledPTitle {
            get {
                return ResourceManager.GetString("msjDeteledPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, Es posible que el miembro haya fallecido.
        /// </summary>
        internal static string msjDiedM {
            get {
                return ResourceManager.GetString("msjDiedM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar al menos una de las dos listas, consulte con su administrador.
        /// </summary>
        internal static string msjdoslistas {
            get {
                return ResourceManager.GetString("msjdoslistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de identidad no encontrado.
        /// </summary>
        internal static string msjduico {
            get {
                return ResourceManager.GetString("msjduico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de identidad incorrecto, verifique sus credenciales he intentelo de nuevo.
        /// </summary>
        internal static string msjduiin {
            get {
                return ResourceManager.GetString("msjduiin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes del Miembro.
        /// </summary>
        internal static string msjduimiembrotitle {
            get {
                return ResourceManager.GetString("msjduimiembrotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de documento de identidad necesario.
        /// </summary>
        internal static string msjduinecesario {
            get {
                return ResourceManager.GetString("msjduinecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de documento de identidad o Código OCR no ha sido ingresado.
        /// </summary>
        internal static string msjduiocr {
            get {
                return ResourceManager.GetString("msjduiocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de identidad incorrecto, verifique sus credenciales he intentelo de nuevo.
        /// </summary>
        internal static string msjduipuser {
            get {
                return ResourceManager.GetString("msjduipuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de identidad no encontrado.
        /// </summary>
        internal static string msjduipusertitle {
            get {
                return ResourceManager.GetString("msjduipusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string msjE {
            get {
                return ResourceManager.GetString("msjE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado.
        /// </summary>
        internal static string msjeliusu {
            get {
                return ResourceManager.GetString("msjeliusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado no pudo ser eliminado debido a que existen datos dependientes.
        /// </summary>
        internal static string msjEmployedP {
            get {
                return ResourceManager.GetString("msjEmployedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso interrumpido.
        /// </summary>
        internal static string msjEmployedPTitle {
            get {
                return ResourceManager.GetString("msjEmployedPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar imágenes.
        /// </summary>
        internal static string msjerima {
            get {
                return ResourceManager.GetString("msjerima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de inserción.
        /// </summary>
        internal static string msjerint {
            get {
                return ResourceManager.GetString("msjerint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar al menos una de las cuatro listas, consulte con su administrador.
        /// </summary>
        internal static string msjerrocag {
            get {
                return ResourceManager.GetString("msjerrocag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        internal static string msjerrorconexion {
            get {
                return ResourceManager.GetString("msjerrorconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la lista del Estado del grupo de opciones, consulte con su administrador.
        /// </summary>
        internal static string msjErrorListP {
            get {
                return ResourceManager.GetString("msjErrorListP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la lista de estado de miembros, consulte con el administrador.
        /// </summary>
        internal static string msjErrorM {
            get {
                return ResourceManager.GetString("msjErrorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error en el momento de revisar horas.
        /// </summary>
        internal static string msjerrorrevisarhora {
            get {
                return ResourceManager.GetString("msjerrorrevisarhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar al menos una de las tres listas, consulte con el administrador.
        /// </summary>
        internal static string msjerrortreslistas {
            get {
                return ResourceManager.GetString("msjerrortreslistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de selección.
        /// </summary>
        internal static string msjerselecio {
            get {
                return ResourceManager.GetString("msjerselecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado está inactivo, espere el tiempo de bloqueo o pongase en contacto con su administrador.
        /// </summary>
        internal static string msjestadoinactivo {
            get {
                return ResourceManager.GetString("msjestadoinactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado inactivo.
        /// </summary>
        internal static string msjestadoinactivotitle {
            get {
                return ResourceManager.GetString("msjestadoinactivotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excelente! el usuario ingresado ya existe en la base de datos, su nueva contraseña ha sido enviada a su correo, Usuario Encontrado.
        /// </summary>
        internal static string msjexele {
            get {
                return ResourceManager.GetString("msjexele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de querer eliminar a:.
        /// </summary>
        internal static string msjextraño {
            get {
                return ResourceManager.GetString("msjextraño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string msjextraño2 {
            get {
                return ResourceManager.GetString("msjextraño2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan imágenes de opciones.
        /// </summary>
        internal static string msjfalta {
            get {
                return ResourceManager.GetString("msjfalta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para configurar la organización asegúrese de ingresar todos los campos y cargar una imagen.
        /// </summary>
        internal static string msjfaltadatapu {
            get {
                return ResourceManager.GetString("msjfaltadatapu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltante.
        /// </summary>
        internal static string msjfaltadataputitle {
            get {
                return ResourceManager.GetString("msjfaltadataputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Faltantes.
        /// </summary>
        internal static string msjfaltan {
            get {
                return ResourceManager.GetString("msjfaltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes de ingresar, verifique que todos los campos esten llenos.
        /// </summary>
        internal static string msjFieldsP {
            get {
                return ResourceManager.GetString("msjFieldsP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos faltantes de la consulta.
        /// </summary>
        internal static string msjfieldspu {
            get {
                return ResourceManager.GetString("msjfieldspu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de opción necesaria.
        /// </summary>
        internal static string msjimagencandidato {
            get {
                return ResourceManager.GetString("msjimagencandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen faltante de ingresar, verifique que ha agregado una imagen.
        /// </summary>
        internal static string msjImageP {
            get {
                return ResourceManager.GetString("msjImageP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen faltante.
        /// </summary>
        internal static string msjImagePTitle {
            get {
                return ResourceManager.GetString("msjImagePTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su cuenta ha sido actualizada a un estado inactiva.
        /// </summary>
        internal static string msjinactiva {
            get {
                return ResourceManager.GetString("msjinactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado actualizado.
        /// </summary>
        internal static string msjinactivatitle {
            get {
                return ResourceManager.GetString("msjinactivatitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo incorrecto.
        /// </summary>
        internal static string msjinco {
            get {
                return ResourceManager.GetString("msjinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de inserción.
        /// </summary>
        internal static string msjinserterror {
            get {
                return ResourceManager.GetString("msjinserterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembro no pudo ser ingresado.
        /// </summary>
        internal static string msjInsertM {
            get {
                return ResourceManager.GetString("msjInsertM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de opciones no pudo ser ingresado.
        /// </summary>
        internal static string msjInsertP {
            get {
                return ResourceManager.GetString("msjInsertP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser ingresado.
        /// </summary>
        internal static string msjinsertusererror {
            get {
                return ResourceManager.GetString("msjinsertusererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tendra 5 oportunidades dentro de 3 minutos, por favor espere.
        /// </summary>
        internal static string msjintentosesperar {
            get {
                return ResourceManager.GetString("msjintentosesperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tendra 5 oportunidades más dentro de 3 minutos.
        /// </summary>
        internal static string msjintentosesperarmas {
            get {
                return ResourceManager.GetString("msjintentosesperarmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante.
        /// </summary>
        internal static string msjintentosesperartitle {
            get {
                return ResourceManager.GetString("msjintentosesperartitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha acabado el tiempo de espera, tiene 5 intentos más.
        /// </summary>
        internal static string msjintentosmas {
            get {
                return ResourceManager.GetString("msjintentosmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo terminado.
        /// </summary>
        internal static string msjintentosmastitle {
            get {
                return ResourceManager.GetString("msjintentosmastitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo tiene .
        /// </summary>
        internal static string msjintentosrestantes1 {
            get {
                return ResourceManager.GetString("msjintentosrestantes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  intentos para acceder..
        /// </summary>
        internal static string msjintentosrestantes2 {
            get {
                return ResourceManager.GetString("msjintentosrestantes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al ingresar.
        /// </summary>
        internal static string msjintentosrestantestitle {
            get {
                return ResourceManager.GetString("msjintentosrestantestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la lista de mesas de votación, consulte con el administrador.
        /// </summary>
        internal static string msjJRVfailed {
            get {
                return ResourceManager.GetString("msjJRVfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativo de la mesa de votación incorrecto, verifique sus credenciales e intentelo de nuevo.
        /// </summary>
        internal static string msjJRVincorrecto {
            get {
                return ResourceManager.GetString("msjJRVincorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa de votación no encontrada.
        /// </summary>
        internal static string msjJRVincorrectoTitle {
            get {
                return ResourceManager.GetString("msjJRVincorrectoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa de votación no pudo ser ingresada.
        /// </summary>
        internal static string msjJRVnoingresada {
            get {
                return ResourceManager.GetString("msjJRVnoingresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar las listas.
        /// </summary>
        internal static string msjlistas {
            get {
                return ResourceManager.GetString("msjlistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una o mas listas no pudieron ser cargadas en el sistema.
        /// </summary>
        internal static string msjlistasnocargadas {
            get {
                return ResourceManager.GetString("msjlistasnocargadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario ingresado, usuario root ha sido creado.
        /// </summary>
        internal static string msjloggedpuser {
            get {
                return ResourceManager.GetString("msjloggedpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación exitosa.
        /// </summary>
        internal static string msjloggedpusertitle {
            get {
                return ResourceManager.GetString("msjloggedpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son requeridos.
        /// </summary>
        internal static string msjLogin {
            get {
                return ResourceManager.GetString("msjLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo no encontrado.
        /// </summary>
        internal static string msjmailno {
            get {
                return ResourceManager.GetString("msjmailno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, el miembro que desea ingresar es menor de edad.
        /// </summary>
        internal static string msjMenorM {
            get {
                return ResourceManager.GetString("msjMenorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, es Miembro de una mesa de votación.
        /// </summary>
        internal static string msjmiembro {
            get {
                return ResourceManager.GetString("msjmiembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El miembro ingresado tiene un estado inactivo.
        /// </summary>
        internal static string msjMinactivo {
            get {
                return ResourceManager.GetString("msjMinactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser actualizado.
        /// </summary>
        internal static string msjnoactualizado {
            get {
                return ResourceManager.GetString("msjnoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de actualización.
        /// </summary>
        internal static string msjnoactualizadotitle {
            get {
                return ResourceManager.GetString("msjnoactualizadotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario ingresario, usuario votante ha sido creado.
        /// </summary>
        internal static string msjnoi {
            get {
                return ResourceManager.GetString("msjnoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código OCR incorrecto, verifique sus credenciales he intentelo de nuevo.
        /// </summary>
        internal static string msjOCR {
            get {
                return ResourceManager.GetString("msjOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código OCR no ha sido encontrado.
        /// </summary>
        internal static string msjOCRTitle {
            get {
                return ResourceManager.GetString("msjOCRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al establecer conexión con la base de datos, verifique
        ///su acceso a internet o que los servicios del servidor estén activos.
        /// </summary>
        internal static string msjocubase {
            get {
                return ResourceManager.GetString("msjocubase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un problema al agregar la boleta.
        /// </summary>
        internal static string msjocubol {
            get {
                return ResourceManager.GetString("msjocubol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, Grupo de opciones.
        /// </summary>
        internal static string msjpartido {
            get {
                return ResourceManager.GetString("msjpartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coinciden.
        /// </summary>
        internal static string msjpassbadpuser {
            get {
                return ResourceManager.GetString("msjpassbadpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas incorrectas.
        /// </summary>
        internal static string msjpassbadpusertitle {
            get {
                return ResourceManager.GetString("msjpassbadpusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se perdió la conexión con la base de datos.
        /// </summary>
        internal static string msjperdioconexion {
            get {
                return ResourceManager.GetString("msjperdioconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        internal static string msjperdioconexiontitle {
            get {
                return ResourceManager.GetString("msjperdioconexiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, Supervisor.
        /// </summary>
        internal static string msjpresi {
            get {
                return ResourceManager.GetString("msjpresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu voto se registró correctamente en el sistema.
        /// </summary>
        internal static string msjprocom {
            get {
                return ResourceManager.GetString("msjprocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Interrumpido.
        /// </summary>
        internal static string msjproint {
            get {
                return ResourceManager.GetString("msjproint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso completado.
        /// </summary>
        internal static string msjproint2 {
            get {
                return ResourceManager.GetString("msjproint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro eliminado.
        /// </summary>
        internal static string msjregistroeliminado {
            get {
                return ResourceManager.GetString("msjregistroeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no pudo ser eliminado debido a que existen datos dependientes.
        /// </summary>
        internal static string msjregistronoeliminado {
            get {
                return ResourceManager.GetString("msjregistronoeliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, su nivel de acceso es: Root.
        /// </summary>
        internal static string msjroot {
            get {
                return ResourceManager.GetString("msjroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asegurese de guardar todos los datos para evitar perdidas de información.
        /// </summary>
        internal static string msjseguro {
            get {
                return ResourceManager.GetString("msjseguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Aplicación.
        /// </summary>
        internal static string msjsegurotitle {
            get {
                return ResourceManager.GetString("msjsegurotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al seleccionar una celda vacia\n\nintente Seleccionar una celda con un dato existente.
        /// </summary>
        internal static string msjselec {
            get {
                return ResourceManager.GetString("msjselec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, la organización no ha sido configurada.
        /// </summary>
        internal static string msjtribnocreatepu {
            get {
                return ResourceManager.GetString("msjtribnocreatepu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas incongruentes.
        /// </summary>
        internal static string msjtribnocreateputitle {
            get {
                return ResourceManager.GetString("msjtribnocreateputitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, la fecha de fundación no es válida para la organización.
        /// </summary>
        internal static string msjtribnoexistpu {
            get {
                return ResourceManager.GetString("msjtribnoexistpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen faltante de la organización.
        /// </summary>
        internal static string msjtribuimgpu {
            get {
                return ResourceManager.GetString("msjtribuimgpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al cargar la imagen de la organización.
        /// </summary>
        internal static string msjtribunal {
            get {
                return ResourceManager.GetString("msjtribunal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La organización no pudo ser configurada.
        /// </summary>
        internal static string msjtribunalerrorpu {
            get {
                return ResourceManager.GetString("msjtribunalerrorpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una o más imágenes de las opciones no fueron cargadas.
        /// </summary>
        internal static string msjunai {
            get {
                return ResourceManager.GetString("msjunai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser actualizado.
        /// </summary>
        internal static string msjUpdM {
            get {
                return ResourceManager.GetString("msjUpdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de opciones no pudo ser actualizado.
        /// </summary>
        internal static string msjUpdP {
            get {
                return ResourceManager.GetString("msjUpdP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o clave incorrecto, verifique sus credenciales.
        /// </summary>
        internal static string msjuserdenied {
            get {
                return ResourceManager.GetString("msjuserdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado un usuario, verifique si ha ingresado el usuario correcto.
        /// </summary>
        internal static string msjusernoencontrado {
            get {
                return ResourceManager.GetString("msjusernoencontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario incorrecto.
        /// </summary>
        internal static string msjusernoencontradotitle {
            get {
                return ResourceManager.GetString("msjusernoencontradotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario, no pudo ser actualizado el registro.
        /// </summary>
        internal static string msjusuarionoactualizado {
            get {
                return ResourceManager.GetString("msjusuarionoactualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser ingresado.
        /// </summary>
        internal static string msjusunop {
            get {
                return ResourceManager.GetString("msjusunop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no pudo ser actualizado.
        /// </summary>
        internal static string msjusunop2 {
            get {
                return ResourceManager.GetString("msjusunop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacios.
        /// </summary>
        internal static string msjvaciotitle {
            get {
                return ResourceManager.GetString("msjvaciotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error de verificación, consulte con su administrador..
        /// </summary>
        internal static string msjverificar {
            get {
                return ResourceManager.GetString("msjverificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de error.
        /// </summary>
        internal static string msjverificarTitle {
            get {
                return ResourceManager.GetString("msjverificarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, Auditor.
        /// </summary>
        internal static string msjvice {
            get {
                return ResourceManager.GetString("msjvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, Votante.
        /// </summary>
        internal static string msjvotante {
            get {
                return ResourceManager.GetString("msjvotante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voto no pudo ser ingresado.
        /// </summary>
        internal static string msjvtin {
            get {
                return ResourceManager.GetString("msjvtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voto registrado.
        /// </summary>
        internal static string msjvtin2 {
            get {
                return ResourceManager.GetString("msjvtin2", resourceCulture);
            }
        }
    }
}
